name: Run Appium tests on BrowserStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
        working-directory: android
      - name: Run Appium tests on BrowserStack
        run: npm run test:browserstack
        working-directory: android

      - name: Create Jira Subtask
        run: |
          DATE=$(date +'%Y-%m-%d %H:%M:%S')
          curl -X POST \
            -H "Content-Type: application/json" \
            -u ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN }} \
            --data "{\n              \"fields\": {\n                \"project\": { \"key\": \"KAN\" },\n                \"parent\": { \"key\": \"KAN-74\" },\n                \"summary\": \"Nightly Run - $DATE\",\n                \"description\": \"Nightly regression run triggered via GitHub Actions. Full report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\",\n                \"issuetype\": { \"id\": \"10003\" }\n              }\n            }" \
            https://tejendrabrowserstack.atlassian.net/rest/api/2/issue
